services:
  jenkins:
    container_name: jenkins
    image: docker.mgkim.net/jenkins:2.535-jdk17
    restart: unless-stopped
    ports:
      - 8082:8080
      - 50000:50000
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /data/cicd/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd_net

networks:
  cicd_net:
    external: true