services:
  nginx:
    container_name: nginx
    image: nginx:1.29
    restart: unless-stopped
    ports:
      - 172.28.200.102:80:80
      - 172.28.200.102:443:443
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /app/certs/server/spring.develop.crt:/etc/nginx/certs/spring.develop.crt:ro
      - /app/certs/server/spring.develop.key:/etc/nginx/certs/spring.develop.key:ro
      - /app/certs/ca/developCA.crt:/etc/nginx/certs/developCA.crt:ro
    networks:
      - app_net
    environment:
      TZ: UTC
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/log/nginx
      - /var/cache/nginx

networks:
  app_net:
    external: true
