services:
  cp-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15-1-ubi8
    container_name: cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - cp-zookeeper_secrets:/etc/zookeeper/secrets
      - cp-zookeeper_data:/var/lib/zookeeper/data
      - cp-zookeeper_log:/var/lib/zookeeper/log
    restart: always
    network_mode: host
    #networks:
    #  - local-default

  cp-kafka:
    image: confluentinc/cp-kafka:7.2.15-1-ubi8

    container_name: cp-kafka
    ports:
      - 29092:29092
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://127.0.0.1:9092,EXTERNAL://172.28.200.101:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - cp-kafka_secrets:/etc/kafka/secrets
      - cp-kafka_data:/var/lib/kafka/data
    depends_on:
      - cp-zookeeper
    network_mode: host
    #networks:
    #  - local-default

volumes:
  cp-zookeeper_secrets:
  cp-zookeeper_data:
  cp-zookeeper_log:
  cp-kafka_secrets:
  cp-kafka_data:

networks:
  local-default:
    external: true
