services:
  nexus:
    image: sonatype/nexus3:3.82.0-java17-alpine
    restart: unless-stopped
    container_name: nexus
    ports:
      - 8081:8081
      - 5000:5000
    environment:
      #- INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
      - INSTALL4J_ADD_VM_PARAMS=-Xms256m -Xmx768m -XX:MaxDirectMemorySize=256m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    volumes:
      - nexus_data:/nexus-data
    network_mode: host
    #networks:
    #  - local-default

volumes:
  nexus_data:

networks:
  local-default:
    external: true
