receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  file:
    path: /etc/output/logs.json
  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true
  otlp/elastic:
    endpoint: "apm-server:8200"
    tls:
      insecure: true

processors:
  batch:
    timeout: 5s

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1888"
  zpages:
    endpoint: "0.0.0.0:55679"

service:
  telemetry:
    logs:
      level: "info"
    metrics:
      level: "detailed"
      address: "0.0.0.0:9463"
  
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic, prometheus]

    traces:
      receivers: [otlp]
      #processors: [batch]
      processors: []
      exporters: [otlp/elastic]

  extensions: [health_check, pprof, zpages]
