services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:3.4.2
    restart: unless-stopped
    ports:
      - 9411:9411
    networks:
      - apm_net
    environment:
      - STORAGE_TYPE=mem

networks:
  apm_net:
    external: true
